[tox]
envlist = py312-format, py312-type

[testenv]
basepython = python3.12
skip_install = true
allowlist_externals = uv

[testenv:py312-format]
basepython = python3.12
skip_install = true
commands =
    uv run ruff check .

[testenv:py312-type]
basepython = python3.12
skip_install = true
commands =
    uv run mypy .
